//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectMatch
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo1_
    {
        public string HomeState { get; set; }
        public string FirstName { get; set; }
        public string Phone { get; set; }
        public string University { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
    }
}
